const express = require("express")

const { cartId } = require("../../middlewares/client/cart.middlewares")
const category = require("../../middlewares/client/category.middlewares")
const { register, registerPost, login, loginPost, logout, forgotPassword, forgotPasswordPost, otpPassword, otpPasswordPost, resetPassword, resetPasswordPost, info } = require("../../controllers/client/user.controller")
const { validateRegister, validateLogin, validateForgotPassword, validateResetPassword } = require("../../validates/clients/user.validate")
const { infoUser } = require("../../middlewares/client/user.middlewares")
const { requireAuthClient } = require("../../middlewares/client/auth.middlewares")
const { settingGeneral } = require("../../middlewares/client/setting.middlewares")


const routerUser = express.Router()
routerUser.use(category)
routerUser.use(cartId)
routerUser.use(infoUser)
routerUser.use(settingGeneral)
routerUser.get("/register", register)
routerUser.post("/register", validateRegister, registerPost)
routerUser.get("/login", login)
routerUser.post("/login", validateLogin, loginPost)
routerUser.get("/logout", logout)
routerUser.get("/password/forgot", forgotPassword)
routerUser.post("/password/forgot", validateForgotPassword, forgotPasswordPost)
routerUser.get("/password/otp", otpPassword)
routerUser.post("/password/otp", otpPasswordPost)
routerUser.get("/password/reset", resetPassword)
routerUser.post("/password/reset", validateResetPassword, resetPasswordPost)
routerUser.get("/info",requireAuthClient, info)
module.exports = routerUser